# -*- coding: utf-8 -*-
cities = {
'AL': ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery'],
'AK': 'Anchorage',
'AZ': ['Chandler', 'Gilbert', 'Glendale', 'Mesa', 'Peoria', 'Phoenix', 'Scottsdale', 'Surprise', 'Tempe', 'Tucson'],
'AR': 'Little Rock',
'CA': ['Anaheim', 'Antioch', 'Bakersfield', 'Berkeley', 'Burbank', 'Carlsbad', 'Chula Vista', 'Concord', 'Corona',
        'Costa Mesa', 'Daly City', 'Downey', 'El Cajon', 'El Monte', 'Elk Grove', 'Escondido', 'Fairfield', 'Fontana',
        'Fremont', 'Fresno', 'Fullerton', 'Garden Grove', 'Glendale', 'Hayward', 'Huntington Beach', 'Inglewood', 'Irvine',
        'Lancaster', 'Long Beach', 'Los Angeles', 'Modesto', 'Moreno Valley', 'Murrieta', 'Norwalk', 'Oakland', 'Oceanside',
        'Ontario', 'Orange', 'Oxnard', 'Palmdale', 'Pasadena', 'Pomona', 'Rancho Cucamonga', 'Rialto', 'Richmond', 
        'Riverside', 'Roseville', 'Sacramento', 'Salinas', 'San Bernardino', 'San Buenaventura', 'San Diego', 'San Francisco',
        'San Jose', 'Santa Ana', 'Santa Clara', 'Santa Clarita', 'Santa Maria', 'Santa Rosa', 'Simi Valley', 'Stockton',
        'Sunnyvale', 'Temecula', 'Thousand Oaks', 'Torrance', 'Vallejo', 'Victorville', 'Visalia', 'West Covina'],
'CO': ['Arvada', 'Aurora', 'Boulder', 'Centennial', 'Colorado Springs', 'Denver', 'Fort Collins', 'Lakewood', 'Pueblo', 
        'Thornton', 'Westminster'],
'CT': ['Bridgeport', 'Hartford', 'New Haven', 'Stamford', 'Waterbury'],
'DC': 'Washington',
'DE': 'Wilmington',
'FL': ['Cape Coral', 'Clearwater', 'Coral Springs', 'Fort Lauderdale', 'Gainesville', 'Hialeah', 'Hollywood', 'Jacksonville',
        'Miami', 'Miami Gardens', 'Miramar', 'Orlando', 'Palm Bay', 'Pembroke Pines', 'Pompano Beach', 'Port St. Lucie',
        'St. Petersburg', 'Tallahassee', 'Tampa', 'West Palm Beach'],
'GA': ['Athens', 'Atlanta', 'Augusta', 'Columbus', 'Savannah'],
'HI': 'Honolulu',
'ID': 'Boise',
'IL': ['Aurora', 'Chicago', 'Elgin', 'Joliet', 'Naperville', 'Peoria', 'Rockford', 'Springfield'],
'IN': ['Evansville', 'Fort Wayne', 'Indianapolis', 'South Bend'],
'IA': ['Cedar Rapids', 'Davenport', 'Des Moines'],
'KS': ['Kansas City', 'Olathe', 'Overland Park', 'Topeka', 'Wichita'],
'KY': ['Lexington', 'Louisville'],
'LA': ['Baton Rouge', 'Lafayette', 'New Orleans', 'Shreveport'],
'ME': 'Portland',
'MD': 'Baltimore',
'MA': ['Boston', 'Cambridge', 'Lowell', 'Springfield', 'Worcester'],
'MI': ['Ann Arbor', 'Detroit', 'Flint', 'Grand Rapids', 'Lansing', 'Sterling Heights', 'Warren'],
'MN': ['Minneapolis', 'Rochester', 'Saint Paul'],
'MS': 'Jackson',
'MO': ['Columbia', 'Independence', 'Kansas City', 'Springfield', 'St. Louis', 'Columbia', 'Independence',
        'Kansas City', 'Springfield', 'St. Louis'],
'MT': 'Billings',
'NE': ['Lincoln','Omaha'],
'NV': ['Henderson', 'Las Vegas', 'North Las Vegas', 'Reno'],
'NH': 'Manchester',
'NJ': ['Elizabeth', 'Jersey City', 'Newark', 'Paterson'],
'NM': ['Albuquerque', 'Las Cruces'],
'NY': ['Buffalo', 'New York', 'Rochester', 'Syracuse', 'Yonkers'],
'NC': ['Cary', 'Charlotte', 'Durham', 'Fayetteville', 'Greensboro', 'High Point', 'Raleigh', 'Wilmington', 'Winston–Salem'],
'ND': 'Fargo',
'OH': ['Akron', 'Cincinnati', 'Cleveland', 'Columbus', 'Dayton', 'Toledo'],
'OK': ['Broken Arrow', 'Norman', 'Oklahoma City', 'Tulsa'],
'OR': ['Eugene', 'Gresham', 'Portland', 'Salem'],
'PA': ['Allentown', 'Erie', 'Philadelphia', 'Pittsburgh'],
'RI': 'Providence',
'SC': ['Charleston', 'Columbia', 'North Charleston'],
'SD': 'Sioux Falls',
'TN': ['Chattanooga', 'Clarksville', 'Knoxville', 'Memphis', 'Murfreesboro', 'Nashville'],
'TX': ['Abilene', 'Amarillo', 'Arlington', 'Austin', 'Beaumont', 'Brownsville', 'Carrollton', 'Corpus Christi', 'Dallas',
        'Denton', 'El Paso', 'Fort Worth', 'Frisco', 'Garland', 'Grand Prairie', 'Houston', 'Irving', 'Killeen', 'Laredo',
        'Lubbock', 'McAllen', 'McKinney', 'Mesquite', 'Midland', 'Odessa', 'Pasadena', 'Plano', 'Richardson',
        'Round Rock', 'San Antonio', 'Waco', 'Wichita Falls'],
'UT': ['Provo', 'Salt Lake City', 'West Jordan', 'West Valley City'],
'VT': 'Burlington',
'VA': ['Alexandria', 'Chesapeake', 'Hampton', 'Newport News', 'Norfolk', 'Richmond', 'Virginia Beach'],
'WA': ['Bellevue', 'Everett', 'Kent', 'Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
'WV': 'Charleston',
'WI': ['Green Bay', 'Kenosha', 'Madison', 'Milwaukee'],
'WY': 'Cheyenne'
}

cities_15 = {
'AL': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Hoover', 'Dothan', 'Decatur',
      'Auburn', 'Madison', 'Florence', 'Gadsden', 'Vestavia Hills', 'Prattville', 'Phenix City'],
'AK': ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan', 'Wasilla', 'Kenai', 'Kodiak', 'Bethel',
        'Palmer', 'Homer', 'Unalaska', 'Barrow', 'Soldotna', 'Valdez'],
'AZ': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Glendale', 'Scottsdale', 'Gilbert', 'Tempe', 'Peoria',
        'Surprise', 'Yuma', 'Avondale', 'Flagstaff', 'Goodyear', 'Lake Havasu City'], 
'AR': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway',
        'Rogers', 'Pine Bluff', 'Bentonville', 'Hot Springs', 'Benton', 'Texarkana', 'Sherwood', 'Jacksonville'],
'CA': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland',
        'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Chula Vista', 'Fremont'],
'CO': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster',
        'Pueblo', 'Centennial', 'Boulder', 'Greeley', 'Longmont', 'Loveland', 'Grand Junction'],
'CT': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain',
        'Bristol', 'Meriden', 'Milford', 'West Haven', 'Middletown', 'Norwich'],
'DE': ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna', 'Milford', 'Seaford', 'Georgetown', 'Elsmere',
        'New Castle', 'Millsboro', 'Laurel', 'Harrington', 'Camden', 'Clayton'],
'DC': ['Washington'],
'FL': ['Jacksonville', 'Miami', 'Tampa', 'St. Petersburg', 'Orlando', 'Hialeah', 'Tallahassee', 'Fort Lauderdale',
        'Port St. Lucie', 'Pembroke Pines', 'Cape Coral', 'Hollywood', 'Gainesville', 'Miramar', 'Coral Springs'],
'GA': ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Sandy Springs', 'Macon', 'Roswell', 'Albany', 'Johns Creek',
        'Warner Robins', 'Alpharetta', 'Marietta', 'Valdosta', 'Smyrna'],
'HI': ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu', 'Kāne‘ohe', 'Mililani Town', 'Kahului', '‘Ewa Gentry',
        'Kīhei'],
'ID': ['Boise', 'Nampa', 'Meridian', 'Idaho Falls', 'Pocatello', 'Caldwell', "Coeur d'Alene", 'Twin Falls', 'Lewiston',
        'Post Falls', 'Rexburg', 'Moscow', 'Eagle', 'Kuna', 'Mountain Home'],
'IL': ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville', 'Springfield', 'Peoria', 'North Peoria', 'Elgin', 'Waukegan'],
'IN': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Bloomington', 'Fishers', 'Hammond', 'Gary',
        'Muncie', 'Lafayette', 'Terre Haute', 'Kokomo', 'Anderson', 'Noblesville'],
'IA': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Waterloo', 'Council Bluffs', 'Ames',
        'West Des Moines', 'Dubuque', 'Ankeny', 'Urbandale', 'Cedar Falls', 'Marion', 'Bettendorf'],
'KS': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe', 'Lawrence', 'Shawnee', 'Manhattan', 'Lenexa',
        'Salina', 'Hutchinson', 'Leavenworth', 'Leawood', 'Dodge City', 'Garden City'],
'KY': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville', 'Richmond', 'Florence',
        'Georgetown', 'Elizabethtown', 'Nicholasville', 'Henderson', 'Jeffersontown', 'Frankfort', 'Paducah'],
'LA': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Metairie', 'Lafayette', 'Lake Charles', 'Kenner', 'Bossier City',
        'Monroe', 'Alexandria', 'Houma', 'Marrero', 'New Iberia', 'Laplace', 'Slidell'], 
'ME': ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford', 'Sanford', 'Augusta', 'Saco',
        'Westbrook', 'Waterville', 'Presque Isle', 'Brewer', 'Bath', 'Caribou'],
'MD': ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie', 'Hagerstown', 'Annapolis', 'College Park',
        'Salisbury', 'Laurel', 'Greenbelt', 'Cumberland', 'Westminster', 'Hyattsville', 'Takoma Park'],
'MA': ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn',
        'Fall River', 'Newton', 'Lawrence', 'Somerville', 'Framingham', 'Haverhill'],
'MI': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor', 'Flint', 'Dearborn',
        'Livonia', 'Clinton', 'Canton', 'Westland', 'Troy', 'Farmington Hills', 'Macomb'],
'MN': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'St. Cloud',
        'Eagan', 'Woodbury', 'Maple Grove', 'Eden Prairie', 'Coon Rapids', 'Burnsville', 'Blaine'],
'MS': ['Jackson', 'West Gulfport', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi', 'Meridian', 'Tupelo',
        'Greenville', 'Olive Branch'],
'MO': ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', "Lee's Summit", "O'Fallon", 'St. Joseph',
        'St. Charles', 'St. Peters', 'Blue Springs', 'Florissant', 'Joplin', 'Chesterfield', 'Jefferson City'],
'MT': ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte', 'Helena', 'Kalispell', 'Havre', 'Anaconda',
        'Miles City', 'Belgrade', 'Livingston', 'Laurel', 'Whitefish', 'Lewistown'],
'NE': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont', 'Hastings', 'North Platte', 'Norfolk',
        'Columbus', 'Papillion', 'La Vista', 'Scottsbluff', 'South Sioux City', 'Beatrice'],
'NV': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City', 'Fernley', 'Elko', 'Mesquite',
        'Boulder City', 'Fallon', 'Winnemucca', 'West Wendover', 'Ely', 'Yerington'],
'NH': ['Manchester', 'Nashua', 'Concord', 'Derry', 'Dover', 'Rochester', 'Salem', 'Merrimack', 'Hudson', 'Londonderry',
        'Keene', 'Bedford', 'Portsmouth', 'Goffstown', 'Laconia'],
'NJ': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison', 'Woodbridge Township', 'Lakewood Township', 'Toms River',
        'Hamilton', 'Trenton', 'Clifton', 'Camden', 'Brick Township', 'Cherry Hill', 'Passaic'],
'NM': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell', 'Farmington', 'South Valley', 'Clovis', 'Hobbs', 
        'Alamogordo', 'Carlsbad', 'Gallup', 'Los Alamos', 'Deming', 'Los Lunas'],
'NY': ['New York', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady',
        'Utica', 'White Plains', 'Troy', 'Niagara Falls', 'Binghamton', 'Rome'],
'NC': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Wilmington',
        'High Point', 'Greenville', 'Asheville', 'Concord', 'Gastonia', 'Jacksonville', 'Chapel Hill'],
'ND': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo', 'Dickinson', 'Mandan', 'Williston', 'Jamestown',
        'Wahpeton', 'Devils Lake', 'Valley City', 'Grafton', 'Beulah', 'Rugby'],
'OH': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Canton', 'Youngstown', 'Lorain',
        'Hamilton', 'Springfield', 'Kettering', 'Elyria', 'Lakewood'],
'OK': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Lawton', 'Edmond', 'Moore', 'Midwest City', 'Enid',
        'Stillwater', 'Muskogee', 'Bartlesville', 'Owasso', 'Shawnee', 'Ponca City'],
'OR': ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro', 'Beaverton', 'Bend', 'Medford', 'Springfield', 'Corvallis',
        'Albany', 'Tigard', 'Lake Oswego', 'Keizer', 'Grants Pass'],
'PA': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg',
        'Altoona', 'York', 'State College', 'Wilkes-Barre', 'Chester', 'Williamsport'],
'RI': ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence', 'Woonsocket', 'North Providence', 'West Warwick',
        'Newport', 'Bristol'],
'SC': ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill', 'Greenville', 'Summerville', 'Sumter',
        'Hilton Head Island', 'Florence'],
'SD': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell', 'Yankton', 'Pierre', 'Huron',
        'Vermillion', 'Spearfish', 'Brandon', 'Box Elder', 'Sturgis', 'Madison'],
'TN': ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Jackson', 'Johnson City',
        'Franklin', 'Bartlett', 'Hendersonville', 'Kingsport', 'Collierville', 'Cleveland', 'Smyrna'],
'TX': ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano',
        'Laredo', 'Lubbock', 'Garland', 'Irving', 'Amarillo', 'Grand Prairie'],
'UT': ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem', 'Sandy', 'Ogden', 'St. George', 'Layton',
        'Taylorsville', 'South Jordan', 'Logan', 'Lehi', 'Murray', 'Bountiful'],
'VT': ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier', 'Winooski', 'St. Albans', 'Newport',
        'Vergennes'],
'VA': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News', 'Alexandria', 'Hampton', 'Roanoke',
        'Portsmouth', 'Suffolk', 'Lynchburg', 'Harrisonburg', 'Charlottesville', 'Danville', 'Manassas'],
'WA': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Yakima', 'Federal Way', 
        'Spokane Valley', 'Bellingham', 'Kennewick', 'Auburn', 'Pasco'],
'WV': ['Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling', 'Weirton', 'Fairmont', 'Beckley', 'Martinsburg',
        'Clarksburg', 'South Charleston', 'St. Albans', 'Vienna', 'Bluefield', 'Moundsville'],
'WI': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Oshkosh', 'Eau Claire',
        'Janesville', 'West Allis', 'La Crosse', 'Sheboygan', 'Wauwatosa', 'Fond du Lac'],
'WY': ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan', 'Green River', 'Evanston', 'Riverton',
        'Jackson', 'Cody', 'Rawlins', 'Lander', 'Torrington', 'Powell']
}